import random
import string
from dataclasses import dataclass, field


def generate_id() -> str:
    """
    Generates a random 15-character string of lowercase letters.
    """
    return "".join(random.choices(string.ascii_lowercase, k=15))


@dataclass
class Student:
    """
    A class representing a student with basic information and generated
        credentials.

    Attributes:
    name (str): The student's first name.
    surname (str): The student's surname.
    active (bool): A flag indicating if the student is active (default is
                True).
    login (str): A unique login identifier for the student, automatically gen-
                erated as the first letter of the name followed by the surname.
    id (str): A unique identifier for the student, automatically generated by
            the `generate_id` function.

    Methods:
    __post_init__(): This method is automatically called after the object is
                    initialized, and it generates the student's login based
                    on their name and surname.
    """
    name: str
    surname: str
    active: bool = True
    login: str = field(init=False)
    id: str = field(default_factory=generate_id, init=False)

    def __post_init__(self):
        """
        Initializes the login attribute by combining the first letter of the
        name with the surname.

        This method is automatically called after the object is created and is
        responsible for generating the login string.
        """
        self.login = self.name[0] + self.surname
